# pod
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers: # List
    - name: myapp
      image: ghcr.io/stacksimplify/kubenginx:1.0.0
      ports: 
        - containerPort: 80


---    
# lb
apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer